-- presensi_table.sql
CREATE DATABASE IF NOT EXISTS presensi_pppk DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE presensi_pppk;

CREATE TABLE IF NOT EXISTS absensi (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255) NOT NULL,
  nip VARCHAR(100) NOT NULL,
  status VARCHAR(50) DEFAULT 'Hadir',
  keterangan VARCHAR(255) DEFAULT '',
  foto_masuk VARCHAR(255) DEFAULT NULL,
  foto_pulang VARCHAR(255) DEFAULT NULL,
  lat_masuk VARCHAR(50) DEFAULT NULL,
  lon_masuk VARCHAR(50) DEFAULT NULL,
  lat_pulang VARCHAR(50) DEFAULT NULL,
  lon_pulang VARCHAR(50) DEFAULT NULL,
  tanggal VARCHAR(20) DEFAULT NULL,
  jam_masuk VARCHAR(20) DEFAULT NULL,
  jam_pulang VARCHAR(20) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
